name: Deploy a site to github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    permissions:
      contents: write
      pages: write
      id-token: write

    environment:
      name: development
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: deploy
        id: development
        uses: actions/deploy-pages@v1
